### ISSUE TITLE
Fixes for upcoming hdmf version

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/neuroconv#1147]
Dev tests are failing for several reasons due to changes on the dev branch of hdmf.

- [x] Compound dtypes should be fixed by #1146

The deprecated `call_docval_func` function has been removed, but still lingering on some extensions:
- [x] ndx-pose should be fixed by #1128 
- [x] ndx-events should be fixed by #1176

**Comment by h-mayorquin** [comment]
Should this be closed?
